### PR TITLE
72 useredit docs

### PR DESCRIPTION
**Pull request by skoooch**

### CODE REVIEW

**Review by vvickychan — APPROVED** [review]
Javadocs look good to me!

**Review by carolinexuxy — APPROVED** [review]
All Javadoc includes some description for the function and the parameters, if any. Looks good!

**Review by czhang0312 — APPROVED** [review]
Overall lgtm! The tests you wrote are very comprehensive.

**Review by vvickychan — APPROVED** [review]
Just the approval-- comments were left earlier

**Review by carolinexuxy — APPROVED** [review]
All Javadoc includes some description for the function and the parameters, if any. Looks good!

**Pull request merged**
