### PR TITLE
UserRegPresenter & UserReg Use Case

### PR DESCRIPTION
**Pull request by vvickychan**
Requires LogInView to finish the presenter

The general structure and flow of the use case are present. Need to go through still because making some changes

### CODE REVIEW

**Review by czhang0312 — APPROVED** [review]
In the UserFactory file, you have the class UserFactory defined twice, you only need one (probably just a mistake). Otherwise I think the rest looks good. I see that the structure of your code is really similar to the UserLoginCleanArchitecture example we saw in class, which means that there shouldn't be any issues with clean architecture. One thing I'm not sure about is whether you would have the userRegGateway, userFactory, and presenter as an attribute in the UserRegInteractor or if you would create the objects in the create method instead. However this shouldn't be a big deal, I think we will figure this out when we compile all the code together to see which design pattern works best.

**Review by skoooch — APPROVED** [review]

**Review by kcccr123 — APPROVED** [review]
looks good to me

**Review by skoooch — COMMENTED** [review]
These use cases look great and seem to follow the clean architecture user reg example well

**Comment by carolinexuxy** [comment]
The code is really clean and should be good to work with. One notice from there is that in the useRegInteractor is that the UseRegPresenter does not actually have any prepareView method. So perhaps you should be calling the udpateView with the string as input?

**Pull request merged**
