### PR TITLE
Edited entire project to function, as well I add the code Vicky has d…

### PR DESCRIPTION
**Pull request by skoooch**
…one on UserReg area, becuase her branch had a lot of merge error.

Got functionality of sending messages, creating chatrooms, like dislike working.

Vickys Code Info: Completed the use case for registering a new user. Implemented the presenter for user registration. Began adding javadocs, but need to continue and finish still.

### CODE REVIEW

**Review by Ary4m3n — APPROVED** [review]
Everything looks good and the program is running well with all the interfaces switching and set well. Seems like with few additions on the LogIn and the SignUp pages, we will have a project which is good to be presented.

**Review by whyismynamerudy — APPROVED** [review]
Based off of the discussion we had about changing some functions so that they worked with other files when linking everything together, I agree with the changes you've made, especially with the changes you've made to ChatRepoUseCase. I realize that this was because we had been developing all these files separately to each other and had to link them together at the end - if we had consistently linked and checked during production, we may not have had to do this. For example, I agree with having to search through all the chatrooms stored in currChatrooms to find the specific ones that match with set of users needed.

**Comment by carolinexuxy** [comment]
Everything looks clean and handled all aspects that we initially planned for it. I might make some changes to the UserReg parts when connecting this with the SingUpView.

**Review by carolinexuxy — APPROVED** [review]

**Review by czhang0312 — APPROVED** [review]
These are some major changes to ChatView and it looks good. I didn't take into account that the messages had to be re-rendered every time that you send a message and also re-rendering the chat messages when a new chatroom is selected. I'll take a look at all the changes in more detail once these changes are pulled.

**Pull request merged**
