### PR TITLE
45 java docs and tests for chatview chatviewpresenter chatrenderusecase

### PR DESCRIPTION
**Pull request by czhang0312**
Completed Javadocs and tests for chatview chatviewpresenter chatrenderusecase

### CODE REVIEW

**Review by whyismynamerudy — APPROVED** [review]
LGTM, I agree with your tests. They provide enough code coverage to correctly test the necessary functionality.

**Review by kcccr123 — DISMISSED** [review]
LGTM good coverage on tests

**Review by skoooch — APPROVED** [review]
LGTM

**Review by whyismynamerudy — APPROVED** [review]
LGTM! Thanks for managing the merge conflict that arose in the previous PR. As before, your tests look good.

**Review by vvickychan — APPROVED** [review]
Javadocs look good! Also the tests seem have provide good coverage

**Pull request merged**
